=== ArtemHalushka/ShopJDBC/src/main/resources/xml/xsd/buyer.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="buyerType">
        <xs:sequence>
            <xs:element name="buyerName" type="xs:string"/>
            <xs:element name="phoneNumber" type="xs:string"/>
            <xs:element name="address" type="addressType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="countryType">
        <xs:sequence>
            <xs:element name="countryName" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="cityType">
        <xs:sequence>
            <xs:element name="cityName" type="xs:string"/>
            <xs:element name="country" type="countryType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="firstLine" type="xs:string"/>
            <xs:element name="secondLine" type="xs:string"/>
            <xs:element name="zipCode" type="xs:string"/>
            <xs:element name="city" type="cityType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>

    <xs:element name="buyer" type="buyerType"/>

</xs:schema>

=== ArtemHalushka/ShopJDBC/src/main/resources/xml/buyer.xml
<?xml version="1.0" encoding="UTF-8"?>

<buyer id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="xsd/buyer.xsd">
    <buyerName>Ivan Semenov</buyerName>
    <phoneNumber>123333333</phoneNumber>
    <address id="1">
        <firstLine>123 th se</firstLine>
        <secondLine>apt 4</secondLine>
        <zipCode>123123</zipCode>
        <city id="1">
            <cityName>Moscow</cityName>
            <country id="1">
                <countryName>Russia</countryName>
            </country>
        </city>
    </address>
</buyer>
